# Generated by Django 4.0.1 on 2022-07-22 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_cast_birthday_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 11, 20, 28, 717557)),
        ),
    ]
